Models/dishes_Context.cs
namespace CrudDelicious.Models;

/* 
Disabled Warning: "Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable."
We can disable this safely because we know the framework will assign non-null values when it constructs this class for us.
*/
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
// the MyContext class representing a session with our MySQL database, allowing us to query for or save data
 //same as the name space that you give in the program file
// this change from MyContext to DB
public class DB: DbContext{

    public DB(DbContextOptions options):base(options){}
     // the "Monsters" table name will come from the DbSet property name

    public DbSet<dishes> dish {get; set;}
}

Models/dishes_model.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
//your namespace
namespace CrudDelicious.Models;
//classname
public class dishes
{
//this is the primary key
    [Key]
    public int DishId { get; set; }
//change the field as needed
    [Required]
    [MinLength(2)]
    [MaxLength(45)]
    [Display(Name = "Dish Name")]
    public string Name { get; set; }
    [Required]
    [MinLength(2)]
    [MaxLength(45)] 
    [Display(Name = "Chef Name")] 
    public string Chef { get; set; }
// you need to use range if you want a specific number to be added
        [Required]
        [Range(1,5)]
    public int Tastiness { get; set; }

    [Required]
    [Range(1,Int32.MaxValue)]

    public int Calories { get; set; }
    [Required]
    [MinLength(2)]
    public string Description{get;set;}
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;
}

Controllers/dishes_Controller.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CrudDelicious.Models;

namespace CrudDelicious.Controllers;

public class dishesController : Controller
{
    //here we are setting a private instance of our DB class in our dishes_Context.cs file
    private DB _context;//_context can be what ever we want         it works i test it 

    //* here we are injecting  our context service into the constructor
    // we are making a constructor
    public dishesController (DB context){
        _context = context;
    }
    [HttpGet("")]
    public IActionResult Index()
    {
        // here we are creating a List<> of dishes  and assigning it  to _context.dish(variableName in dishesContext.cs).ToList(); 
        List<dishes> allDishes = _context.dish.ToList();


        return View("Index",allDishes);
    }

    [HttpGet("/dish/new")]
    public IActionResult New(){
        return View("New");
    }
    [HttpPost("/dish/create")]
    // we are creating new dishes instances thats why we are passing  dishes as datatype for our parameter 
    public IActionResult create(dishes newDish){
        if(ModelState.IsValid == false){
            return New();
        }
        //* this only runs if our modelState is valid
        //this is saying  go to my DB folder then the variable that is call dish and add a new dish
        // this adds it to list of post but i does not saves it in the data base yet 
        _context.dish.Add(newDish);
        // * this saves it in the data base
        _context.SaveChanges();
        return Redirect("/");
    }
    [HttpGet("/dish/view/{dishId}")]
    // we are passing the id to the url
    public IActionResult view_one(int dishId){
        // here we are searching for the first id that matches  then setting it to be the on tha we put on the url
        dishes? id = _context.dish.FirstOrDefault(id => id.DishId == dishId);
        // here we are checking if the id is == to null(does not exist) the we will be redirected the index page
        if(id == null){
            return RedirectToAction("Index");
        }
        //!dont call your file view call it viewOne or something else
        // you need to pass in you id 
        return View("viewOne",id);
    }
    [HttpPost("/dish/delete/{delete}")]
    // this is for deleting 
    public IActionResult delete(int delete){
        // here we are searching for the first id that matches  then setting it to be the on tha we put on the url
        dishes? deleteId = _context.dish.FirstOrDefault(dish => dish.DishId == delete);
        // if it finds something the it will delete it 
        if(deleteId != null){
            _context.dish.Remove(deleteId);
            _context.SaveChanges();
        }
        // Else it will  redirect you to the index page
        return RedirectToAction("Index");
        

    }

    [HttpGet("/dish/edit/{edit}")]

    public IActionResult edit(int edit){
         // here we are searching for the first id that matches  then setting it to be the on tha we put on the url
        dishes? editId = _context.dish.FirstOrDefault(dish => dish.DishId == edit);
        //if it finds nothing then it will redirect you to the index page 
        if(editId == null){
            return RedirectToAction("Index");
        }
        // else it will render the edit page
        return View("edit",editId);
    }

    [HttpPost("/dish/update/{UpdatedDishId}")]
    public IActionResult update( int UpdatedDishId,dishes UpdatedDish){
        if(ModelState.IsValid == false){
            //* you can do all the logic bello in 1 line by calling the get edit function that you made above because its already doing the logic in the edit function
            return edit(UpdatedDishId);
            // * long way to doit
            // dishes? originalDish = _context.dish.FirstOrDefault(dish => dish.DishId == UpdatedDish.DishId);
            // if(originalDish == null){
            //     return RedirectToAction("index");
            // }
            // return View("edit",originalDish);
        }
        //here we are searching for the first id that matches  then setting it to be the on tha we put on the url
        dishes? originalDish = _context.dish.FirstOrDefault(dish => dish.DishId == UpdatedDishId);
        //if it finds nothing then it will redirect you to the index page 
        if(originalDish == null){
            return RedirectToAction("index");
        }
        // this are the thing that we are updating
        originalDish.Name = UpdatedDish.Name;
        originalDish.Chef = UpdatedDish.Chef;
        originalDish.Calories = UpdatedDish.Calories;
        originalDish.Tastiness = UpdatedDish.Tastiness;
        originalDish.Description = UpdatedDish.Description;
        originalDish.UpdatedAt = DateTime.Now;
        _context.dish.Update(originalDish);
        _context.SaveChanges();
        // 
            // return RedirectToAction("Index",originalDish.DishId);
        return view_one(originalDish.DishId);
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudDelicious</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudDelicious.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudDelicious</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CrudDelicious - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/dishes/Index.cshtml
@model List<dishes>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>All dishes</h1>
    <a href="/dish/new"> Add dish</a>
    @* * add the view one later *@
    @foreach (var item in Model){
        @* * we can chage the name of out url  because this is calling the controller then the name of the funtion then adding the DishId  
        altho i perfer the normal a tag*@
        <h6>  <a  asp-controller="dishes" asp-action="view_one" asp-route-DishId="@item.DishId" > @item.Name</a>  created by @item.Chef </h6> 
        <form action="/dish/delete/@item.DishId" method="post"> <button>Delete</button></form>
        <a href="/dish/edit/@item.DishId"><button>update</button></a>

    }
    
</body>
</html> 

Views/dishes/New.cshtml
@model dishes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/">Home</a>
    <form action="/dish/create" method="post">
        <div>
            <label asp-for="Name"></label>
            <span asp-validation-for="Name" ></span>
        </div>
        <input type="text" asp-for="Name" id="">
        <div>
            <label asp-for="Chef"></label>
            <span asp-validation-for="Chef" ></span>
        </div>
        <input type="text" asp-for="Chef" id="">
        <div>
            <label asp-for="Calories"></label>
            <span asp-validation-for="Calories" ></span>
        </div>
        <input type="text" asp-for="Calories" id="">
        <div>
            <label asp-for="Tastiness"></label>
            <span asp-validation-for="Tastiness" ></span>
        </div>
        <select asp-for="Tastiness" id="">
            <option value="">Select</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
        <div>
            <label asp-for="Description"></label>
            <span asp-validation-for="Description" ></span>
        </div>
        <input type="text" asp-for="Description" id="">
        <div>
            <button>create Dish</button>
        </div>

    </form>
    
</body>
</html>

Views/dishes/edit.cshtml
@model dishes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <a href="/">Home</a>
    <form action="/dish/update/@Model.DishId" method="post">
        <div>
            <label asp-for="Name"></label>
            <span asp-validation-for="Name" ></span>
        </div>
        <input type="text" asp-for="Name" value="@Model.Name" placeholder="@Model.Name" id="">
        <div>
            <label asp-for="Chef"></label>
            <span asp-validation-for="Chef" ></span>
        </div>
        <input type="text" asp-for="Chef"value="@Model.Chef" placeholder="@Model.Chef"  id="">
        <div>
            <label asp-for="Calories"></label>
            <span asp-validation-for="Calories" ></span>
        </div>
        <input type="text" asp-for="Calories" value="@Model.Calories" placeholder="@Model.Calories"  id="">
        <div>
            <label asp-for="Tastiness"></label>
            <span asp-validation-for="Tastiness" ></span>
        </div>
        <select asp-for="Tastiness" id="">
            <option value="">Select</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
        <div>
            <label asp-for="Description"></label>
            <span asp-validation-for="Description" ></span>
        </div>
        <input type="text" asp-for="Description"value="@Model.Description" placeholder="@Model.Description"  id="">
        <div>
            <button>Update  Dish</button>
        </div>

    </form>
</body>
</html>

Views/dishes/viewOne.cshtml
@model dishes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/">Home</a>
    <h1>Dish id: @Model.DishId</h1>
    <div></div>
    <h3>Chef Name: @Model.Chef</h3>
    <h3>Dish Name: @Model.Name</h3>
    <h3>Tastiness: @Model.Tastiness</h3>
    <h3>Description: @Model.Description</h3>

    <form action="/dish/delete/@Model.DishId" method="post"> <button>Delete</button></form>


</body>
</html>